version: "3"
services:
  rabbitmq:
    network_mode: 'host'
    hostname: "rabbitmq-host"
    image: rabbitmq:3.8.9-alpine
    container_name: rabbit_mq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_ERLANG_COOKIE=cookie
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    network_mode: 'host'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 5050
    volumes:
       - pgadmin:/root/.pgadmin

    ports:
      - "5050:5050"
  database:
    network_mode: 'host'
    image: postgres:alpine
    # restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER : root
    ports:
      - 5432:5432 
    volumes:
       - postgres:/data/postgres
volumes:
    postgres:
    pgadmin:
