version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
#  adminmongo:
#    image: mongo-express
#    environment:
#    - CONFIG_MONGODB_ADMINUSERNAME="root"
#    - ME_CONFIG_MONGODB_ADMINPASSWORD="rootpassword"
#    ports:
#      - 8081:8081

volumes:
  mongodb_data_container: